markdown: kramdown
permalink: pretty

title: IS&E Repo

college: PES College of Engineering
department: Information Science and Engineering
place: Mandya

collections:
  sem:
    output: true

  sub:
    output: true
